name: CI Workflow for Services

on:
  push:
    branches: [ "main", f_**", "fix_**" ]
  pull_request:
    branches: [ "main", f_**", "fix_**" ]

jobs:
  service_ci:
    name: ${{ matrix.service }} CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - book_service
          - llama3_service
          - recommendation_service
          - review_service
          - shared_service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flake8
        run: pip install flake8

      - name: Lint ${{ matrix.service }} with Flake8
        run: flake8 --config=${{ matrix.service }}/.flake8 ${{ matrix.service }}/

      - name: Build Docker image for ${{ matrix.service }}
        run: |
          docker build -t ${{ matrix.service }}-image -f ${{ matrix.service }}/Dockerfile ./${{ matrix.service }}

      - name: Run Pytest for ${{ matrix.service }}
        run: |
          docker run --rm ${{ matrix.service }}-image pytest
